#!/usr/bin/env perl
use Mojolicious::Lite -signatures;

use Time::Duration 'ago_exact';

plugin 'Webpack' => {process => [qw(js css sass)]};

app->defaults(seo_description => 'Create a shareable timer.');

get(
  '/:epoch/:seconds' => {epoch => 0, seconds => 0},
  sub ($c) {
    my $stash = $c->stash;
    $stash->{seo_canonical} = $c->req->url->to_abs;
    $stash->{seo_icon}      = $c->url_for('/images/clock_ballonicon2.png')->to_abs;
    $stash->{seo_site}      = $stash->{seo_canonical}->host;
    $stash->{seo_site} =~ s!\w+\.([^\.]+).*!$1!;

    if (my $ends = $stash->{epoch} + $stash->{seconds}) {
      $stash->{seo_description} = sprintf 'The timer expire%s %s', $ends > time ? 's' : 'd',
        ago_exact(time - $ends);
    }
  },
  'timer'
);

helper alarm_sound => sub ($c, $format) {
  return shift->url_for("/sounds/alarm-clock-soundbible.com-437257341.$format");
};

helper seo => sub ($c, $for, $new_value = undef) {
  my $stash = $c->stash;
  $stash->{"seo_$for"} = $new_value if @_ == 3;
  return $stash->{"seo_$for"} // '';
};

$ENV{X_REQUEST_BASE} and hook before_dispatch => sub {
  my $c = shift;
  return unless my $base = $c->req->headers->header('X-Request-Base');
  $c->req->url->base(Mojo::URL->new($base));
};

app->start;

__DATA__
@@ timer.html.ep
% title 'Timekeeper - Share your timer';
% layout 'default';
% my $index_url = url_for 'timer', {epoch => undef, seconds => undef};
% my @classes = qw(timer-app);
% push @classes, $seconds ? '-countdown' : '-set';

%= form_for $index_url, id => 'app', class => join(' ', @classes), begin
  <h1 class="main-title"><a href="#about">Timekeeper</a></h1>
  <section class="timer-app_fields">
    %= number_field 'd', '0', class => 'timer-app_field -days', min => 0, max => 999, autocomplete => 'off'
    <label class="timer-app_label -days">days</label>
    <span class="timer-app_separator -days">:</span>

    %= number_field 'h', '0', class => 'timer-app_field -hours', min => 0, max => 23, autocomplete => 'off'
    <label class="timer-app_label -hours">hours</label>
    <span class="timer-app_separator -hours">:</span>

    %= number_field 'm', '0', class => 'timer-app_field -minutes', min => 0, max => 59, autocomplete => 'off'
    <label class="timer-app_label -minutes">minutes</label>
    <span class="timer-app_separator -minutes">:</span>

    %= number_field 's', '0', class => 'timer-app_field -seconds', min => 0, max => 59, autocomplete => 'off'
    <label class="timer-app_label -seconds">seconds</label>
  </section>
  <section class="timer-app_progressbar show-when -countdown hide"><div>&nbsp;</div></section>
  <footer class="timer-app_footer show-when -set">
    Set a timer and press play. <button class="btn"><i class="fas fa-play"></i></button>
  </footer>
  <footer class="timer-app_footer show-when -countdown hide">
    <a href="<%= $index_url %>" class="btn set"><i class="fas fa-power-off"></i></a>
    <a href="#toggle/alarm" class="btn"><i class="fas fa-bell"></i></a>
    <a href="#about" class="btn"><i class="fas fa-info-circle"></i></a>
  </footer>
  <footer class="timer-app_footer show-when -expired hide">
    The timer has expired.
    <a href="<%= $index_url %>" class="btn set"><i class="fas fa-redo"></i></a>
  </footer>
  <audio name="player" preload="auto" loop="true" class="timer-app_sound">
    <source src="<%= alarm_sound 'ogg' %>" type="audio/ogg"></source>
    <source src="<%= alarm_sound 'mpeg' %>" type="audio/mpeg"></source>
  </audio>
% end

<article id="about" class="article-about">
  <h1>About Timekeeper</h1>
  <p>
    Timekeeper is an app that allows you to create a shareable countdown timer.
  </p>
  <p>
    Simply copy and paste the URL in your browser to a friend or coworker,
    after <%= link_to 'setting the timer', 'timer' %>.
  </p>

  <p class="text-center">
    <a href="#set:0" class="btn -big">Set a custom timer</a>
  </p>
  <p class="text-center">
    <a href="#set:300" class="btn -secondary">5 min</a>
    <a href="#set:600" class="btn -secondary">10 min</a>
    <a href="#set:3600" class="btn -secondary">1 hour</a>
    <a href="#set:480" class="btn -secondary">Eggs</a>
  </p>

  <h2>Story</h2>
  <p>
    John tells his coworker Jane: <i>"I'll have it done in ten minutes!"</i>
  </p>
  <p>
    Jane replies: <i>"Yeah, right..."</i>
  </p>
  <p>
    John creates a timer and shares the link with Jane, so she can make fun of
    him after ten minutes have gone.
  </p>

  <h2>Idea</h2>
  <p>
    The idea came when my friend kept saying "Yeah, right", and I wanted to
    prove I could do "something" in the amount of time that I had promised.
  </p>

  <h2>Copyright and license</h2>
  <p>
    <a href="https://github.com/jhthorsen/app-timekeeper">This program</a> is
    free software, you can redistribute it and/or modify it under the terms of
    the <a href="https://opensource.org/licenses/Artistic-2.0">Artistic License version 2.0</a>.
  </p>
</article>

<footer class="footer">
  <p class="copyright">&copy; 2014-2018 &mdash; <a href="http://thorsen.pm">Jan Henning Thorsen</a></p>
</footer>
@@ layouts/default.html.ep
<!DOCTYPE html>
<html>

<head>
  <title><%= title %></title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <meta name="twitter:card" content="summary">
  <meta name="twitter:description" content="<%= seo 'description' %>">
  <meta name="twitter:image" content="<%= seo 'icon' %>">
  <meta name="twitter:site" content="<%= seo 'site' %>">
  <meta name="twitter:title" content="<%= title %>">
  <meta name="twitter:url" content="<%= seo 'canonical' %>">
  <meta property="og:description" content="<%= seo 'description' %>">
  <meta property="og:determiner" content="a">
  <meta property="og:image" content="<%= seo 'icon' %>">
  <meta property="og:title" content="<%= title %>">
  <meta property="og:url" content="<%= seo 'canonical' %>">
  %= asset 'timekeeper.css'
  <link rel="shortcut icon" href="<%= seo 'icon' %>" type="image/png">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
</head>
<body>
  %= content
  %= asset 'timekeeper.js'
</body>
</html>
